"""DNS 配置生成器 — 将统一配置模型转写为 dnsmasq 配置文件

响应 'dns' 配置节的变更事件，生成 /etc/dnsmasq.d/ubunturouter.conf。
"""

import logging
from pathlib import Path
from typing import Optional

from ubunturouter.config.models import UbunturouterConfig
from ubunturouter.engine.events import ConfigChangeEvent, GeneratorResult
from ubunturouter.engine.generators.base import BaseGenerator, register_generator

logger = logging.getLogger(__name__)

DNS_CONF = Path("/etc/dnsmasq.d/ubunturouter.conf")
DNSMASQ_D_DIR = Path("/etc/dnsmasq.d")


@register_generator
class DNSGenerator(BaseGenerator):
    """DNS 配置生成器"""

    SECTION = "dns"

    def generate(self, config: UbunturouterConfig) -> GeneratorResult:
        """根据 UbunturouterConfig 生成 dnsmasq 配置"""
        dns = config.dns
        if not dns:
            # DNS 未配置，跳过（不删除已有配置）
            return self.ok("DNS not configured, skipping")

        lines = [
            "# UbuntuRouter DNS Configuration - auto-generated by ConfigEngine",
            f"# Generated at: {__import__('datetime').datetime.now().isoformat()}",
            "",
        ]

        # 上游 DNS 服务器
        if dns.upstream:
            for server in dns.upstream:
                lines.append(f"server={server}")
        lines.append("")

        # DNSSEC
        if dns.enable_dnssec:
            lines.append("dnssec")
            lines.append("dnssec-check-unsigned")
            lines.append("conf-file=/usr/share/dnsmasq-base/trust-anchors.conf")
        lines.append("")

        # 缓存大小
        lines.append(f"cache-size={dns.cache_size}")
        lines.append("")

        # 域名屏蔽
        if dns.blocking and dns.blocklists:
            for bl in dns.blocklists:
                lines.append(f"server=/{bl}/")
                lines.append(f"address=/{bl}/")
        lines.append("")

        # 基本设置
        lines.append("bind-interfaces")
        lines.append("domain-needed")
        lines.append("bogus-priv")
        lines.append("no-resolv")
        lines.append("no-poll")
        lines.append("")

        # 日志
        lines.append("log-queries")
        lines.append("log-facility=/var/log/dnsmasq.log")
        lines.append("")

        content = "\n".join(lines)

        # 原子写入
        if not self.write_file(DNS_CONF, content):
            return self.fail(f"Failed to write {DNS_CONF}")

        # 从 UbunturouterConfig 读取 DHCP 配置，写入 DHCP 相关设置
        if config.dhcp and config.dhcp.interface:
            dhcp_lines = [
                f"interface={config.dhcp.interface}",
                f"dhcp-range={config.dhcp.range_start},{config.dhcp.range_end},{config.dhcp.lease_time}s",
                f"dhcp-option=option:router,{config.dhcp.gateway}",
                f"dhcp-option=option:dns-server,{','.join(config.dhcp.dns)}",
            ]
            if config.dhcp.domain:
                dhcp_lines.append(f"domain={config.dhcp.domain}")

            # 静态绑定
            for lease in config.dhcp.static_leases:
                dhcp_lines.append(
                    f"dhcp-host={lease.mac},{lease.ip}{',' + lease.hostname if lease.hostname else ''}"
                )

            dhcp_lines.append("")
            dhcp_conf = DNSMASQ_D_DIR / "ubunturouter-dhcp.conf"
            self.write_file(dhcp_conf, "\n".join(dhcp_lines))

        # 重载 dnsmasq
        self.reload_service("dnsmasq")

        return self.ok(
            f"DNS config written to {DNS_CONF}",
            files_modified=[str(DNS_CONF)],
        )
