"""Dnsmasq 配置生成器 — DHCP + DNS 综合配置

迁移自 ubunturouter/generators/dnsmasq.py。
响应 "dhcp" 和 "dns" 配置节变更。
"""

import logging
from pathlib import Path
from typing import List, Optional

from ubunturouter.config.models import UbunturouterConfig, DHCPPoolConfig, DNSConfig, StaticLease
from ubunturouter.engine.events import GeneratorResult
from ubunturouter.engine.generators.base import BaseGenerator, register_generator

logger = logging.getLogger(__name__)

OUTPUT_PATH = Path("/etc/dnsmasq.d/ubunturouter.conf")


@register_generator
class DnsmasqGenerator(BaseGenerator):
    """生成 /etc/dnsmasq.d/ubunturouter.conf（DHCP + DNS）"""
    SECTION = "dns"  # 同时覆盖 dhcp 和 dns，但用 dns 作为 primary section

    def generate(self, config: UbunturouterConfig) -> GeneratorResult:
        files_modified = []
        lines = [
            "# Generated by UbuntuRouter",
            "# DHCP + DNS 综合配置",
            "",
        ]

        # DHCP 配置
        if config.dhcp:
            lines += self._gen_dhcp(config.dhcp, config.dns)

        # DNS 配置
        if config.dns:
            lines += self._gen_dns(config.dns)

        if not config.dhcp and not config.dns:
            lines.append("# No DHCP or DNS configured")
            lines.append("port=0")

        lines.append("")
        content = "\n".join(lines)

        if not self.write_file(OUTPUT_PATH, content):
            return self.fail(f"Failed to write {OUTPUT_PATH}")

        files_modified.append(str(OUTPUT_PATH))

        # Validate with dnsmasq --test
        result = self.run_cmd(["dnsmasq", "--test"], timeout=10)
        if not result["success"]:
            logger.warning("dnsmasq --test failed: %s (config written anyway)", result['stderr'])

        # Reload dnsmasq
        if not self.reload_service("dnsmasq"):
            logger.warning("Failed to reload dnsmasq (service may not be running), config written anyway")

        return self.ok("DNS/DHCP configuration applied", files_modified)

    def _gen_dhcp(self, dhcp: DHCPPoolConfig, dns: Optional[DNSConfig]) -> List[str]:
        lines = [
            "# ── DHCP 配置 ──",
            f"interface={dhcp.interface}",
            f"dhcp-range={dhcp.range_start},{dhcp.range_end},{dhcp.lease_time // 3600}h",
            f"dhcp-option=3,{dhcp.gateway}",
        ]
        if dhcp.domain:
            lines.append(f"domain={dhcp.domain}")
        if dns and dns.upstream:
            dns_str = ",".join(dns.upstream)
            lines.append(f"dhcp-option=6,{dns_str}")

        for lease in dhcp.static_leases:
            lines.append(f"dhcp-host={lease.mac},{lease.ip},{lease.hostname or ''}")

        lines.append("dhcp-ignore=tag:!known")
        lines.append("dhcp-rapid-commit")

        return lines

    def _gen_dns(self, dns: DNSConfig) -> List[str]:
        lines = [
            "",
            "# ── DNS 配置 ──",
        ]
        if dns.enable_dnssec:
            lines.append("dnssec")
            lines.append("dnssec-check-unsigned")
            lines.append("trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5")
        if dns.upstream:
            for server in dns.upstream:
                lines.append(f"server={server}")
        if dns.cache_size:
            lines.append(f"cache-size={dns.cache_size}")

        lines.append("localise-queries")
        lines.append("domain-needed")
        lines.append("bogus-priv")
        lines.append("expand-hosts")
        lines.append("no-resolv")
        lines.append("bind-interfaces")

        return lines
