"""防火墙配置生成器 — 将统一配置模型转写为 nftables 规则集

响应 'firewall' 配置节的变更事件，生成 nftables 规则文件并加载。
"""

import logging
from pathlib import Path

from ubunturouter.config.models import UbunturouterConfig
from ubunturouter.engine.events import GeneratorResult
from ubunturouter.engine.generators.base import BaseGenerator, register_generator

logger = logging.getLogger(__name__)

NFT_CONF = Path("/etc/nftables.d/ubunturouter.conf")
NFT_TABLE = "ubunturouter"


@register_generator
class FirewallGenerator(BaseGenerator):
    """防火墙配置生成器"""

    SECTION = "firewall"

    def generate(self, config: UbunturouterConfig) -> GeneratorResult:
        """根据 UbunturouterConfig 生成 nftables 配置"""
        fw = config.firewall

        lines = [
            "# UbuntuRouter Firewall - auto-generated by ConfigEngine",
            f"# Generated at: {__import__('datetime').datetime.now().isoformat()}",
            "",
            f"table inet {NFT_TABLE} {{",
        ]

        # ── Chain: forward ─────────────────────────────────
        lines.append("")
        lines.append(f"\tchain forward {{")
        default_fwd = fw.default_policy.get("forward", "drop") if fw.default_policy else "drop"
        lines.append(f"\t\ttype filter hook forward priority 0; policy {default_fwd};")
        lines.append("")

        # Zone-based forwarding rules
        for zone in fw.zones.values():
            if zone.forward_to:
                for target in zone.forward_to:
                    lines.append(f"\t\tiifname \"{zone.name}*\" oifname \"{target}*\" accept")
            if zone.isolated:
                lines.append(f"\t\tiifname \"{zone.name}*\" oifname \"{zone.name}*\" drop")

        # Port forwards (DNAT)
        for pf in fw.port_forwards:
            if not pf.enabled:
                continue
            proto = pf.protocol.replace("_", "-") if pf.protocol else "tcp"
            to_port = pf.to_port if pf.to_port else pf.from_port
            lines.append(
                f"\t\tiifname \"{pf.from_zone}*\" {proto} dport {pf.from_port} "
                f"dnat to {pf.to_ip}:{to_port}"
            )

        # Custom rules
        for rule in fw.rules:
            if not rule.enabled:
                continue
            cond = ""
            if rule.protocol:
                cond += f" {rule.protocol}"

            if rule.src_ip:
                cond += f" ip saddr {rule.src_ip}"
            if rule.dst_ip:
                cond += f" ip daddr {rule.dst_ip}"
            if rule.src_port and rule.protocol in ("tcp", "udp", "tcp_udp"):
                cond += f" {rule.protocol.split('_')[0]} sport {rule.src_port}"
            if rule.dst_port and rule.protocol in ("tcp", "udp", "tcp_udp"):
                cond += f" {rule.protocol.split('_')[0]} dport {rule.dst_port}"

            action_map = {"accept": "accept", "drop": "drop", "reject": "reject with icmp admin-prohibited", "log": "log"}
            action = action_map.get(rule.action, "accept")
            lines.append(f"\t\t{cond} {action}".strip())

        lines.append("\t}")

        # ── Chain: input ──────────────────────────────────
        lines.append("")
        lines.append("\tchain input {")
        default_in = fw.default_policy.get("input", "drop") if fw.default_policy else "drop"
        lines.append(f"\t\ttype filter hook input priority 0; policy {default_in};")
        lines.append("\t\tiif lo accept")
        lines.append("\t\tct state established,related accept")
        lines.append("\t\tip protocol icmp accept")
        lines.append("\t}")

        # ── Chain: output ─────────────────────────────────
        lines.append("")
        lines.append("\tchain output {")
        default_out = fw.default_policy.get("output", "accept") if fw.default_policy else "accept"
        lines.append(f"\t\ttype filter hook output priority 0; policy {default_out};")
        lines.append("\t}")

        # ── Chain: postrouting (MASQUERADE for zones) ─────
        masq_zones = [z.name for z in fw.zones.values() if z.masquerade]
        if masq_zones:
            lines.append("")
            lines.append("\tchain postrouting {")
            lines.append("\t\ttype nat hook postrouting priority 100;")
            for z in masq_zones:
                lines.append(f"\t\toifname \"{z}*\" masquerade")
            lines.append("\t}")

        # ── Chain: prerouting (DNAT) ──────────────────────
        dnat_rules = [pf for pf in fw.port_forwards if pf.enabled]
        if dnat_rules:
            lines.append("")
            lines.append("\tchain prerouting {")
            lines.append("\t\ttype nat hook prerouting priority 0;")
            for pf in dnat_rules:
                proto = pf.protocol.replace("_", "-") if pf.protocol else "tcp"
                lines.append(f"\t\tiifname \"{pf.from_zone}*\" {proto} dport {pf.from_port} dnat to {pf.to_ip}:{pf.to_port or pf.from_port}")
            lines.append("\t}")

        lines.append("}")
        lines.append("")

        content = "\n".join(lines)

        if not self.write_file(NFT_CONF, content):
            return self.fail(f"Failed to write {NFT_CONF}")

        # 加载 nftables 规则
        r = self.run_cmd(["nft", "-f", str(NFT_CONF)])
        if not r["success"]:
            return self.fail(f"nftables load failed: {r['stderr']}")

        return self.ok(
            f"Firewall rules written to {NFT_CONF}",
            files_modified=[str(NFT_CONF)],
        )
