"""Dnsmasq 配置生成器 — DHCP + DNS"""

from typing import Dict, Optional
from ..config.models import UbunturouterConfig, DHCPPoolConfig, DNSConfig, StaticLease
from .base import ConfigGenerator


OUTPUT_PATH = "/etc/dnsmasq.d/ubunturouter.conf"


class DnsmasqGenerator(ConfigGenerator):
    """生成 dnsmasq 配置"""

    def __init__(self):
        self.output_path = OUTPUT_PATH

    def generate(self, config: UbunturouterConfig) -> Dict[str, str]:
        lines = [
            f"# Generated by UbuntuRouter",
            f"# DHCP + DNS 综合配置",
            "",
        ]

        # DHCP 配置
        if config.dhcp:
            lines += self._gen_dhcp(config.dhcp, config.dns)

        # DNS 配置
        if config.dns:
            lines += self._gen_dns(config.dns)

        # 如果没有 DHCP 也没有 DNS，生成最小配置
        if not config.dhcp and not config.dns:
            lines.append("# No DHCP or DNS configured")
            lines.append("port=0")

        lines.append("")
        return {self.output_path: "\n".join(lines)}

    def validate_generated(self, content: str) -> Optional[str]:
        return None  # dnsmasq --test 在 apply 时验证

    def reload_command(self) -> List[str]:
        return ["systemctl", "reload-or-restart", "dnsmasq"]

    def reload_delay(self) -> int:
        return 200

    # ─── 内部方法 ────────────────────────────────────────

    def _gen_dhcp(self, dhcp: DHCPPoolConfig, dns: Optional[DNSConfig]) -> List[str]:
        lines = [
            "# ── DHCP 配置 ──",
            f"interface={dhcp.interface}",
            f"dhcp-range={dhcp.range_start},{dhcp.range_end},{dhcp.lease_time}h",
            f"dhcp-option=3,{dhcp.gateway}",
        ]
        if dhcp.domain:
            lines.append(f"domain={dhcp.domain}")
        if dns and dns.upstream:
            dns_str = ",".join(dns.upstream)
            lines.append(f"dhcp-option=6,{dns_str}")

        # 静态租约
        for lease in dhcp.static_leases:
            lines.append(f"dhcp-host={lease.mac},{lease.ip},{lease.hostname or ''}")

        # 只响应已知接口的 DHCP 请求
        lines.append(f"dhcp-ignore=tag:!known")
        lines.append(f"dhcp-rapid-commit")

        return lines

    def _gen_dns(self, dns: DNSConfig) -> List[str]:
        lines = [
            "",
            "# ── DNS 配置 ──",
        ]
        if dns.enable_dnssec:
            lines.append("dnssec")
            lines.append("dnssec-check-unsigned")
            lines.append("trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5")
        if dns.upstream:
            for server in dns.upstream:
                lines.append(f"server={server}")
        if dns.cache_size:
            lines.append(f"cache-size={dns.cache_size}")

        # 本地域名解析
        lines.append("localise-queries")
        lines.append("domain-needed")
        lines.append("bogus-priv")
        lines.append("expand-hosts")
        lines.append("no-resolv")
        lines.append("bind-interfaces")

        return lines
