"""Nftables 配置生成器 — Zone/NAT/端口转发"""

from typing import Dict, List, Optional
from ..config.models import (
    UbunturouterConfig, FirewallConfig, FirewallZoneConfig,
    PortForwardRule, FirewallRule, InterfaceConfig, InterfaceRole,
    FirewallPolicy,
)
from .base import ConfigGenerator


OUTPUT_PATH = "/etc/nftables.d/ubunturouter.conf"
TABLE_NAME = "ubunturouter"


class NftablesGenerator(ConfigGenerator):
    """生成 nftables 规则集"""

    def __init__(self):
        self.output_path = OUTPUT_PATH

    def generate(self, config: UbunturouterConfig) -> Dict[str, str]:
        lines = [
            "#!/usr/sbin/nft -f",
            f"# Generated by UbuntuRouter — {TABLE_NAME} ruleset",
            "",
            f"table inet {TABLE_NAME} {{",
        ]

        # Set definitions (for IP sets, interface groups)
        lines += self._gen_sets(config)

        # Chains
        lines += self._gen_chains(config)

        lines += "}"
        lines.append("")
        return {self.output_path: "\n".join(lines)}

    def validate_generated(self, content: str) -> Optional[str]:
        return None  # nft -c 在 apply 时验证

    def reload_command(self) -> List[str]:
        return ["nft", "-f", OUTPUT_PATH]

    def reload_delay(self) -> int:
        return 500

    # ─── 内部方法 ────────────────────────────────────────

    def _gen_sets(self, config: UbunturouterConfig) -> List[str]:
        lines = []
        fw = config.firewall

        # Zone interface sets
        for zone_name, zone in fw.zones.items():
            ifaces = self._zone_interfaces(config, zone.name)
            if ifaces:
                lines.append(f"\t# Zone: {zone.name}")
                lines.append(f"\tset iface_{zone.name} {{")
                lines.append("\t\ttype ifname")
                lines.append("\t\telements = { " + ", ".join(ifaces) + " }")
                lines.append("\t}")
        return lines

    def _gen_chains(self, config: UbunturouterConfig) -> List[str]:
        lines = []
        fw = config.firewall

        # --- Input chain ---
        lines.append("")
        lines.append("\tchain input {")
        lines.append("\t\ttype filter hook input priority 0; policy drop;")
        lines.append("")
        lines.append("\t\t# Allow established/related")
        lines.append("\t\tct state established,related counter accept")
        lines.append("")
        lines.append("\t\t# Allow loopback")
        lines.append("\t\tiif lo accept")
        lines.append("")

        # Zone input rules
        for zone_name, zone in fw.zones.items():
            lines.append(f"\t\t# Zone {zone.name} input")
            if zone.input == FirewallPolicy.ACCEPT:
                lines.append(f"\t\tiif @iface_{zone.name} counter accept")
            elif zone.input == FirewallPolicy.REJECT:
                lines.append(f"\t\tiif @iface_{zone.name} counter reject")

        # Custom input rules
        for rule in fw.rules:
            if rule.direction == "input":
                lines.append(f"\t\t# Rule: {rule.name or 'custom'}")
                rule_str = self._rule_to_nft(rule)
                if rule_str:
                    lines.append(f"\t\t{rule_str}")

        lines.append("\t}")

        # --- Forward chain ---
        lines.append("")
        lines.append("\tchain forward {")
        lines.append("\t\ttype filter hook forward priority 0; policy drop;")
        lines.append("")

        # Zone forward rules (zone isolation)
        for zone_name, zone in fw.zones.items():
            if zone.isolated:
                # 隔离 zone 之间互访
                for fwd_to in zone.forward_to:
                    lines.append(f"\t\t# Zone {zone.name} -> {fwd_to}")
                    lines.append(f"\t\tiif @iface_{zone.name} oif @iface_{fwd_to} counter drop")
            else:
                # 允许 zone 访问其他 zone
                for fwd_to in zone.forward_to:
                    lines.append(f"\t\t# Zone {zone.name} -> {fwd_to}")
                    lines.append(f"\t\tiif @iface_{zone.name} oif @iface_{fwd_to} counter accept")

        # LAN→WAN 默认允许（流量出口）
        wan_ifaces = self._role_ifaces(config, InterfaceRole.WAN)
        lan_zones = set()
        for i in config.interfaces:
            if i.role in (InterfaceRole.LAN, InterfaceRole.GUEST, InterfaceRole.WANLAN):
                if i.firewall_zone:
                    lan_zones.add(i.firewall_zone)

        for lan_zone in lan_zones:
            for wan_zone in self._role_zones(config, InterfaceRole.WAN):
                # 如果已经在 zone 的 forward_to 中允许了就不重复
                zone_obj = fw.zones.get(lan_zone)
                if zone_obj and wan_zone in zone_obj.forward_to:
                    continue  # 已在 zone forward rules 中处理
                lines.append(f"\t\tiif @iface_{lan_zone} oif @iface_{wan_zone} counter accept")

        # Forward rules from config
        for rule in fw.rules:
            if rule.direction == "forward":
                lines.append(f"\t\t# Rule: {rule.name or 'custom'}")
                rule_str = self._rule_to_nft(rule)
                if rule_str:
                    lines.append(f"\t\t{rule_str}")

        # Port forward rules (实际上在 DNAT 处理，forward 链放行转发的流量)
        for pf in fw.port_forwards:
            iface_names = self._zone_iface_names(config, pf.from_zone)
            for name in iface_names:
                lines.append(f"\t\t# Port forward {pf.name}: {pf.from_port} -> {pf.to_ip}:{pf.to_port}")
                lines.append(f"\t\tiif {name} tcp dport {pf.from_port} ct state new counter accept")

        lines.append("\t}")

        # --- Output chain ---
        lines.append("")
        lines.append("\tchain output {")
        lines.append("\t\ttype filter hook output priority 0; policy accept;")
        lines.append("\t}")

        # --- Postrouting (NAT / Masquerade) ---
        lines.append("")
        lines.append("\tchain postrouting {")
        lines.append("\t\ttype nat hook postrouting priority 100; policy accept;")
        lines.append("")
        for zone_name, zone in fw.zones.items():
            if zone.masquerade:
                wan_ifaces_nat = self._role_ifaces(config, InterfaceRole.WAN)
                for wan_iface in wan_ifaces_nat:
                    lines.append(f"\t\t# Masquerade for {zone.name} via {wan_iface}")
                    lines.append(f"\t\toif {wan_iface} masquerade")

        lines.append("\t}")

        # --- Prerouting (DNAT / Port Forward) ---
        lines.append("")
        lines.append("\tchain prerouting {")
        lines.append("\t\ttype nat hook prerouting priority 0; policy accept;")
        lines.append("")
        for pf in fw.port_forwards:
            iface_names = self._zone_iface_names(config, pf.from_zone)
            for name in iface_names:
                lines.append(f"\t\t# Port forward {pf.name}")
                proto = pf.protocol or "tcp"
                lines.append(f"\t\tiif {name} {proto} dport {pf.from_port} dnat to {pf.to_ip}:{pf.to_port}")

        lines.append("\t}")

        return lines

    def _rule_to_nft(self, rule: FirewallRule) -> str:
        """将 FirewallRule 转换为 nftables 规则字符串"""
        parts = []
        if rule.src_ip:
            parts.append(f"ip saddr {rule.src_ip}")
        if rule.dst_ip:
            parts.append(f"ip daddr {rule.dst_ip}")
        if rule.src_port:
            parts.append(f"tcp sport {rule.src_port}")
        if rule.dst_port:
            parts.append(f"{rule.protocol or 'tcp'} dport {rule.dst_port}")
        if rule.protocol and rule.protocol not in ("tcp", "udp"):
            parts.append(f"meta l4proto {rule.protocol}")

        action = "accept" if rule.action == FirewallPolicy.ACCEPT else "drop" if rule.action == FirewallPolicy.DROP else "reject"
        if rule.log:
            parts.append("log")
        parts.append(f"counter {action}")
        return " ".join(parts)

    def _zone_interfaces(self, config: UbunturouterConfig, zone_name: str) -> List[str]:
        """获取 zone 关联的物理接口名"""
        ifaces = []
        for i in config.interfaces:
            if i.firewall_zone == zone_name:
                if i.device:
                    ifaces.append(i.device)
                if i.ports:
                    ifaces.extend(i.ports)
        return ifaces

    def _zone_iface_names(self, config: UbunturouterConfig, zone_name: str) -> List[str]:
        """获取 zone 关联的 netplan 接口名（含 bridge）"""
        names = set()
        for i in config.interfaces:
            if i.firewall_zone == zone_name:
                if i.role == InterfaceRole.LAN:
                    # LAN 口可能在 bridge 下
                    names.add(f"br-{i.name}")
                    names.add("br-lan")
                elif i.role == InterfaceRole.WANLAN:
                    names.add(f"br-{i.name}")
                    names.add(i.device)
                if i.device:
                    names.add(i.device)
                if i.ports:
                    names.update(i.ports)
        return list(names)

    def _role_ifaces(self, config: UbunturouterConfig, role: InterfaceRole) -> List[str]:
        return [i.device for i in config.interfaces if i.role == role and i.device]

    def _role_zones(self, config: UbunturouterConfig, role: InterfaceRole) -> List[str]:
        zones = set()
        for i in config.interfaces:
            if i.role == role and i.firewall_zone:
                zones.add(i.firewall_zone)
        return list(zones)
